-- Applied to Supabase on 2026-08-14. Returns aggregate-only, current-point-in-time event statistics.
create or replace function public.current_event_statistics()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_event public.events%rowtype;
begin
 if not exists (select 1 from public.user_roles where user_id=auth.uid() and role in ('system_admin','event_manager')) then raise exception '행사 운영 권한이 필요합니다'; end if;
 select * into v_event from public.events where active=true order by event_date desc limit 1;
 if not found then return null; end if;
 return jsonb_build_object('generated_at',now(),'event',jsonb_build_object('title',v_event.title,'event_date',v_event.event_date,'location',v_event.location),
  'summary',jsonb_build_object('capacity',(select coalesce(sum(capacity),0) from public.time_slots where event_id=v_event.id and enabled),'reserved',(select count(*) from public.reservations where event_id=v_event.id and reservation_status<>'cancelled'),'checked_in',(select count(*) from public.reservations where event_id=v_event.id and reservation_status='checked_in'),'no_show',(select count(*) from public.reservations where event_id=v_event.id and reservation_status='no_show'),'cancelled',(select count(*) from public.reservations where event_id=v_event.id and reservation_status='cancelled'),'completed',(select count(*) from public.reservations where event_id=v_event.id and donation_status='completed')+(select count(*) from public.walk_ins where event_id=v_event.id and donation_status='completed'),'reservation_completed',(select count(*) from public.reservations where event_id=v_event.id and donation_status='completed'),'walkin_completed',(select count(*) from public.walk_ins where event_id=v_event.id and donation_status='completed'),'ineligible',(select count(*) from public.reservations where event_id=v_event.id and donation_status='ineligible')+(select count(*) from public.walk_ins where event_id=v_event.id and donation_status='ineligible'),'walkins',(select count(*) from public.walk_ins where event_id=v_event.id)),
  'participants',jsonb_build_object('reservation_employee',(select count(*) from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and participant_type='employee'),'reservation_visitor',(select count(*) from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and participant_type<>'employee'),'walkin_employee',(select count(*) from public.walk_ins where event_id=v_event.id and participant_type='employee'),'walkin_visitor',(select count(*) from public.walk_ins where event_id=v_event.id and participant_type<>'employee')),
  'slots',coalesce((select jsonb_agg(jsonb_build_object('slot_time',s.slot_time,'capacity',s.capacity,'reserved',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status<>'cancelled'),'checked_in',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status='checked_in'),'completed',(select count(*) from public.reservations r where r.slot_id=s.id and r.donation_status='completed'),'ineligible',(select count(*) from public.reservations r where r.slot_id=s.id and r.donation_status='ineligible'),'no_show',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status='no_show')) order by s.slot_time) from public.time_slots s where s.event_id=v_event.id and s.enabled),'[]'::jsonb),
  'workplaces',coalesce((select jsonb_agg(jsonb_build_object('workplace',x.workplace,'count',x.count) order by x.count desc,x.workplace) from (select coalesce(nullif(btrim(workplace),''),'미입력') workplace,count(*)::int count from (select workplace from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and participant_type='employee' union all select workplace from public.walk_ins where event_id=v_event.id and participant_type='employee') p group by 1) x),'[]'::jsonb));
end $$;
revoke execute on function public.current_event_statistics() from public, anon;
grant execute on function public.current_event_statistics() to authenticated;
