-- Run this in Supabase SQL Editor. It replaces current_event_statistics with detail lists for the statistics screen.
create or replace function public.current_event_statistics()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_event public.events%rowtype; v_capacity int; v_reserved int;
begin
 if not exists (select 1 from public.user_roles where user_id=auth.uid() and role in ('system_admin','event_manager')) then raise exception '행사 운영 권한이 필요합니다'; end if;
 select * into v_event from public.events where active=true order by event_date desc limit 1;
 if not found then return null; end if;
 select coalesce(sum(capacity),0)::int into v_capacity from public.time_slots where event_id=v_event.id and enabled;
 select count(*)::int into v_reserved from public.reservations where event_id=v_event.id and reservation_status<>'cancelled';
 return jsonb_build_object(
  'generated_at',now(), 'event',jsonb_build_object('title',v_event.title,'event_date',v_event.event_date,'location',v_event.location),
  'summary',jsonb_build_object(
   'available',greatest(0,v_capacity-v_reserved), 'reserved',v_reserved,
   'cancelled',(select count(*) from public.reservations where event_id=v_event.id and reservation_status='cancelled'),
   'no_show',(select count(*) from public.reservations where event_id=v_event.id and reservation_status='no_show'),
   'completed',(select count(*) from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and donation_status='completed')+(select count(*) from public.walk_ins where event_id=v_event.id and donation_status='completed'),
   'ineligible',(select count(*) from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and donation_status='ineligible')+(select count(*) from public.walk_ins where event_id=v_event.id and donation_status='ineligible'),
   'walkins',(select count(*) from public.walk_ins where event_id=v_event.id),
   'reservation_completed',(select count(*) from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and donation_status='completed'),
   'walkin_completed',(select count(*) from public.walk_ins where event_id=v_event.id and donation_status='completed')),
  'slots',coalesce((select jsonb_agg(jsonb_build_object('slot_time',s.slot_time,'capacity',s.capacity,'reserved',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status<>'cancelled'),'checked_in',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status='checked_in'),'completed',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status<>'cancelled' and r.donation_status='completed'),'ineligible',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status<>'cancelled' and r.donation_status='ineligible'),'no_show',(select count(*) from public.reservations r where r.slot_id=s.id and r.reservation_status='no_show')) order by s.slot_time) from public.time_slots s where s.event_id=v_event.id and s.enabled),'[]'::jsonb),
  'workplaces',coalesce((select jsonb_agg(jsonb_build_object('workplace',x.workplace,'count',x.count) order by x.count desc,x.workplace) from (select coalesce(nullif(btrim(workplace),''),'미입력') workplace,count(*)::int count from (select workplace from public.reservations where event_id=v_event.id and reservation_status<>'cancelled' and participant_type='employee' and donation_status='completed' union all select workplace from public.walk_ins where event_id=v_event.id and participant_type='employee' and donation_status='completed') p group by 1) x),'[]'::jsonb),
  'details',jsonb_build_object(
   'reserved',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'phone',r.phone,'employee_id',r.employee_id,'workplace',r.workplace,'slot_time',s.slot_time,'registration_type','예약','reservation_status',r.reservation_status,'donation_status',r.donation_status) order by s.slot_time,r.name) from public.reservations r join public.time_slots s on s.id=r.slot_id where r.event_id=v_event.id and r.reservation_status<>'cancelled'),'[]'::jsonb),
   'cancelled',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'phone',r.phone,'employee_id',r.employee_id,'workplace',r.workplace,'slot_time',s.slot_time,'registration_type','예약','reservation_status',r.reservation_status,'donation_status',r.donation_status) order by s.slot_time,r.name) from public.reservations r join public.time_slots s on s.id=r.slot_id where r.event_id=v_event.id and r.reservation_status='cancelled'),'[]'::jsonb),
   'no_show',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'phone',r.phone,'employee_id',r.employee_id,'workplace',r.workplace,'slot_time',s.slot_time,'registration_type','예약','reservation_status',r.reservation_status,'donation_status',r.donation_status) order by s.slot_time,r.name) from public.reservations r join public.time_slots s on s.id=r.slot_id where r.event_id=v_event.id and r.reservation_status='no_show'),'[]'::jsonb),
   'completed',coalesce((select jsonb_agg(to_jsonb(x) order by x.registration_type,x.slot_time,x.name) from (select r.id,r.name,r.phone,r.employee_id,r.workplace,s.slot_time,'예약'::text registration_type,r.reservation_status,r.donation_status from public.reservations r join public.time_slots s on s.id=r.slot_id where r.event_id=v_event.id and r.reservation_status<>'cancelled' and r.donation_status='completed' union all select w.id,w.name,w.phone,w.employee_id,w.workplace,null::time,'비예약'::text,'checked_in'::text,w.donation_status from public.walk_ins w where w.event_id=v_event.id and w.donation_status='completed') x),'[]'::jsonb),
   'ineligible',coalesce((select jsonb_agg(to_jsonb(x) order by x.registration_type,x.slot_time,x.name) from (select r.id,r.name,r.phone,r.employee_id,r.workplace,s.slot_time,'예약'::text registration_type,r.reservation_status,r.donation_status from public.reservations r join public.time_slots s on s.id=r.slot_id where r.event_id=v_event.id and r.reservation_status<>'cancelled' and r.donation_status='ineligible' union all select w.id,w.name,w.phone,w.employee_id,w.workplace,null::time,'비예약'::text,'checked_in'::text,w.donation_status from public.walk_ins w where w.event_id=v_event.id and w.donation_status='ineligible') x),'[]'::jsonb),
   'walkins',coalesce((select jsonb_agg(jsonb_build_object('id',w.id,'name',w.name,'phone',w.phone,'employee_id',w.employee_id,'workplace',w.workplace,'slot_time',null,'registration_type','비예약','reservation_status','checked_in','donation_status',w.donation_status) order by w.name) from public.walk_ins w where w.event_id=v_event.id),'[]'::jsonb),
   'reservation_completed',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'phone',r.phone,'employee_id',r.employee_id,'workplace',r.workplace,'slot_time',s.slot_time,'registration_type','예약','reservation_status',r.reservation_status,'donation_status',r.donation_status) order by s.slot_time,r.name) from public.reservations r join public.time_slots s on s.id=r.slot_id where r.event_id=v_event.id and r.reservation_status<>'cancelled' and r.donation_status='completed'),'[]'::jsonb),
   'walkin_completed',coalesce((select jsonb_agg(jsonb_build_object('id',w.id,'name',w.name,'phone',w.phone,'employee_id',w.employee_id,'workplace',w.workplace,'slot_time',null,'registration_type','비예약','reservation_status','checked_in','donation_status',w.donation_status) order by w.name) from public.walk_ins w where w.event_id=v_event.id and w.donation_status='completed'),'[]'::jsonb)));
end $$;

revoke execute on function public.current_event_statistics() from public, anon;
grant execute on function public.current_event_statistics() to authenticated;
