"use client";
import { useState } from "react";
import { Header } from "@/components/Header";
import { supabase, phoneOnly, Slot } from "@/lib/supabase";
import Slots from "@/components/Slots";

const reasons=[['personal','개인 사정'],['schedule','일정 변경'],['health','건강 상태'],['duplicate','중복 예약'],['event_change','행사 일정 변경'],['other','기타']];

export default function Reservation(){
 const [form,setForm]=useState({name:"",phone:"",pin:""}),[reservation,setReservation]=useState<any>(),[slots,setSlots]=useState<Slot[]>([]),[message,setMessage]=useState(""),[pinMode,setPinMode]=useState(false),[newSlot,setNewSlot]=useState(""),[cancelOpen,setCancelOpen]=useState(false),[reason,setReason]=useState(''),[note,setNote]=useState('');
 const find=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const {data,error}=await supabase.rpc('find_reservation',{p_name:form.name,p_phone:phoneOnly(form.phone),p_pin:form.pin});if(error||!data?.ok){setMessage(error?.message||'입력하신 예약정보를 확인해주세요.');return}setReservation(data.reservation);setSlots(data.slots)};
 const change=async()=>{const {data,error}=await supabase.rpc('change_reservation_slot',{p_reservation_id:reservation.id,p_pin:form.pin,p_slot_id:newSlot});if(error||!data?.ok){setMessage(data?.message||error?.message||'시간 변경에 실패했습니다.');return}setMessage('예약 시간이 변경되었습니다.');setReservation(data.reservation);setNewSlot("")};
 const cancel=async()=>{setMessage('');const {data,error}=await supabase.rpc('cancel_reservation',{p_reservation_id:reservation.id,p_pin:form.pin,p_reason:reason,p_note:note});if(error){setMessage(`예약 취소에 실패했습니다: ${error.message}`);return}if(data?.ok){setReservation(null);setCancelOpen(false);setMessage('예약이 취소되었습니다.')}else setMessage(data?.message||'취소 사유를 선택해주세요.')};
 const request=async(e:React.FormEvent)=>{e.preventDefault();const {data,error}=await supabase.rpc('create_pin_request',{p_name:form.name,p_phone:phoneOnly(form.phone)});setMessage(!error&&data?.ok?'PIN 변경 요청이 접수되었습니다. 담당자가 전화 확인 후 처리합니다.':error?.message||'입력하신 정보를 확인해주세요.')};
 if(pinMode)return <main className="page"><Header back/><h1>PIN 변경 요청</h1><p className="hint">이름과 전화번호를 입력하면 담당자가 본인 확인 후 PIN을 변경합니다.</p><form onSubmit={request}><label className="label">이름</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label className="label">전화번호</label><input required inputMode="numeric" value={form.phone} onChange={e=>setForm({...form,phone:phoneOnly(e.target.value)})}/>{message&&<p style={{color:'#1e4fa3'}}>{message}</p>}<button className="btn" style={{marginTop:18}}>PIN 변경 요청</button></form></main>;
 return <main className="page"><Header back/><h1>예약 조회 / 수정</h1>{!reservation?<form onSubmit={find}><p className="hint">예약 시 입력한 정보를 입력해주세요.</p><label className="label">이름</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label className="label">전화번호</label><input required inputMode="numeric" value={form.phone} onChange={e=>setForm({...form,phone:phoneOnly(e.target.value)})}/><label className="label">예약 PIN (숫자 4자리)</label><input required maxLength={4} inputMode="numeric" value={form.pin} onChange={e=>setForm({...form,pin:phoneOnly(e.target.value).slice(0,4)})}/>{message&&<p style={{color:message.includes('취소되었습니다')?'#1e4fa3':'#bd293b'}}>{message}</p>}<button className="btn" style={{marginTop:18}}>조회하기</button></form>:<section><div className="card"><b>{reservation.name}</b><p className="hint">{reservation.event_date} · {reservation.slot_time?.slice(0,5)}<br/>{reservation.location}</p></div><h2 style={{fontSize:'1.1rem',marginTop:25}}>예약 시간 변경</h2><Slots slots={slots} selected={newSlot} onSelect={setNewSlot}/>{newSlot&&<button className="btn" onClick={change}>선택한 시간으로 변경</button>}<button className="btn btn-outline" style={{marginTop:18}} onClick={()=>{setCancelOpen(!cancelOpen);setMessage('')}}>예약 취소</button>{cancelOpen&&<div className="card" style={{marginTop:12}}><label className="label">취소 사유</label><select value={reason} onChange={e=>setReason(e.target.value)}><option value="">선택해주세요</option>{reasons.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select>{reason==='other'&&<><label className="label">기타 사유</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="취소 사유를 입력해주세요"/></>}<button className="btn" onClick={cancel} style={{marginTop:16}}>취소 확정</button>{message&&<p style={{color:message.includes('실패')||message.includes('선택')||message.includes('입력')||message.includes('찾을')?'#bd293b':'#1e4fa3'}}>{message}</p>}</div>}</section>}<button className="btn btn-outline" style={{marginTop:20}} onClick={()=>{setPinMode(true);setMessage('')}}>예약 PIN을 잊으셨나요?</button></main>;
}
