"use client";
import { useEffect, useState } from "react";
import { Header } from "@/components/Header";
import { supabase } from "@/lib/supabase";

export default function LookupPage(){
 const selectedReservationId=typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('reservationId')||'';
 const [rows,setRows]=useState<any[]>([]),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('active');
 const load=async()=>{const {data,error}=await supabase.from('reservations').select('*, time_slots(slot_time)').neq('reservation_status','cancelled').order('created_at',{ascending:false});setRows(data||[]);setMessage(error?`예약 목록을 불러오지 못했습니다: ${error.message}`:'')};
 useEffect(()=>{load()},[]);
 const change=async(id:string,values:any)=>{const {error}=await supabase.from('reservations').update(values).eq('id',id);if(error){setMessage(`처리에 실패했습니다: ${error.message}`);return}setRows(rows.map(row=>row.id===id?{...row,...values}:row));setMessage('처리되었습니다.')};
 const normalized=query.replace(/[^a-zA-Z0-9가-힣]/g,'').toLowerCase();const visible=rows.filter(row=>{const text=[row.name,row.phone,row.employee_id,row.workplace].filter(Boolean).join('').replace(/[^a-zA-Z0-9가-힣]/g,'').toLowerCase();const match=selectedReservationId?row.id===selectedReservationId:(!normalized||text.includes(normalized));const state=filter==='active'?true:filter==='not_checked'?row.reservation_status==='reserved':filter==='checked'?row.reservation_status==='checked_in':filter==='noshow'?row.reservation_status==='no_show':filter==='completed'?row.donation_status==='completed':row.donation_status==='ineligible';return match&&state});return <main className="page admin"><Header/><a href="/admin" style={{color:'#1e4fa3'}}>← 관리자 메뉴</a><h1>{selectedReservationId?'예약자 처리':'예약자 조회·처리'}</h1><p className="hint">{selectedReservationId?'선택한 예약자 1명을 처리합니다.':'이름, 전화번호, 사번 또는 근무처로 찾아 참석·헌혈 상태를 처리합니다.'}</p>{selectedReservationId&&<p><a href="/admin/lookup" className="small-btn" style={{textDecoration:'none'}}>전체 예약자 조회로 돌아가기</a></p>}<section className="card" style={{marginBottom:14}}><input disabled={!!selectedReservationId} value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름 · 전화번호 · 사번 · 근무처 검색"/><select value={filter} onChange={e=>setFilter(e.target.value)} style={{marginTop:8}}><option value="active">전체 예약자</option><option value="not_checked">미처리</option><option value="checked">참석</option><option value="noshow">미참석</option><option value="completed">헌혈완료</option><option value="ineligible">헌혈불가</option></select><p className="hint" style={{marginBottom:0}}>검색 결과 {visible.length}명</p></section>{message&&<p style={{color:message.includes('실패')||message.includes('못')?'#bd293b':'#1e4fa3'}}>{message}</p>}{visible.map(row=><article className="card" key={row.id} style={{marginBottom:12}}><b>{row.name}</b><p className="hint">전화번호 <a href={`tel:${row.phone}`} style={{color:'#1e4fa3'}}>{row.phone}</a><br/>예약시간 {row.time_slots?.slot_time?.slice(0,5)||'-'} · 현재 상태 {row.reservation_status==='no_show'?'미참석':row.donation_status==='completed'?'헌혈완료':row.donation_status==='ineligible'?'헌혈불가':row.reservation_status}{row.participant_type==='employee'&&<><br/>사번 {row.employee_id} · 근무처 {row.workplace}</>}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button className="btn" onClick={()=>change(row.id,{reservation_status:'checked_in',checked_in_at:new Date().toISOString()})}>참석 처리</button><button className="btn btn-outline" onClick={()=>change(row.id,{reservation_status:'no_show'})}>미참석 처리</button><button className="btn" onClick={()=>change(row.id,{donation_status:'completed',completed_at:new Date().toISOString()})}>헌혈완료</button><button className="btn btn-outline" onClick={()=>change(row.id,{donation_status:'ineligible'})}>헌혈불가</button></div></article>)}{!message&&visible.length===0&&<p className="hint">조건에 맞는 예약자가 없습니다.</p>}</main>;
}
