"use client";
import { useEffect, useState } from "react";
import { Header } from "@/components/Header";
import { supabase } from "@/lib/supabase";

const label:{[key:string]:string}={capacity:'예약 가능 인원',reserved:'예약 인원',checked_in:'참석 인원',no_show:'미참석',cancelled:'취소',completed:'헌혈완료 합계',reservation_completed:'예약 헌혈완료',walkin_completed:'비예약 헌혈완료',ineligible:'헌혈불가',walkins:'비예약 헌혈'};
const time=(value?:string)=>value?new Date(value).toLocaleString('ko-KR',{hour12:false}):'-';
const csv=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;

export default function StatisticsPage(){
 const [data,setData]=useState<any>(),[message,setMessage]=useState('');
 const load=async()=>{setMessage('');const [statistics,employees]=await Promise.all([supabase.rpc('current_event_statistics'),supabase.rpc('completed_employee_donors')]);if(statistics.error||employees.error){setMessage(`통계를 불러오지 못했습니다: ${statistics.error?.message||employees.error?.message}`);return}setData({...statistics.data,completedEmployees:employees.data||[]})};
 useEffect(()=>{load()},[]);
 const downloadExcel=()=>{if(!data)return;const rows=[['헌혈행사 요청시점 통계'],['행사명',data.event.title],['헌혈행사일',data.event.event_date],['조회시각',time(data.generated_at)],[],['구분','인원'],...Object.entries(data.summary).map(([key,value])=>[label[key]||key,value]),[],['시간대','예약 가능','예약','참석','헌혈완료','헌혈불가','미참석'],...data.slots.map((s:any)=>[s.slot_time?.slice(0,5),s.capacity,s.reserved,s.checked_in,s.completed,s.ineligible,s.no_show]),[],['직원 근무처','인원'],...data.workplaces.map((w:any)=>[w.workplace,w.count]),[],['헌혈완료 직원 명단','근무처','등록 구분'],...data.completedEmployees.map((employee:any)=>[employee.name,employee.workplace,employee.registration_type])];const file=new Blob(['\uFEFF'+rows.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=`헌혈행사_통계_${data.event.event_date}.csv`;link.click();URL.revokeObjectURL(link.href)};
 if(message)return <main className="page admin"><Header/><a href="/admin" style={{color:'#1e4fa3'}}>← 관리자 메뉴</a><h1>통계</h1><p style={{color:'#bd293b'}}>{message}</p></main>;
 if(!data)return <main className="page admin"><Header/><p className="hint">통계를 불러오는 중입니다.</p></main>;
 return <main className="page admin statistics"><Header/><a className="no-print" href="/admin" style={{color:'#1e4fa3'}}>← 관리자 메뉴</a><div className="statistics-head"><div><h1>헌혈행사 통계</h1><p className="hint">{data.event.title} · 헌혈행사일 {data.event.event_date}<br/>조회 시각: {time(data.generated_at)}</p></div><div className="statistics-actions no-print"><button className="small-btn" onClick={load}>새로고침</button><button className="small-btn" onClick={downloadExcel}>엑셀용 다운로드</button><button className="small-btn" onClick={()=>window.print()}>PDF로 저장</button></div></div><p className="hint no-print">통계는 버튼을 누른 현재 시점의 데이터입니다. 엑셀용 다운로드는 Excel에서 바로 열 수 있는 CSV 파일이며, PDF로 저장은 인쇄 창에서 “PDF로 저장”을 선택합니다.</p><section><h2>종합 현황</h2><div className="admin-grid">{Object.entries(data.summary).map(([key,value])=><div className="stat" key={key}><span className="hint">{label[key]||key}</span><b style={{display:'block',fontSize:'1.3rem',marginTop:7}}>{String(value)}명</b></div>)}</div></section><section className="card" style={{marginTop:18}}><h2>시간대별 현황</h2><table><thead><tr><th>시간</th><th>예약</th><th>참석</th><th>완료</th><th>불가</th><th>미참석</th></tr></thead><tbody>{data.slots.map((s:any)=><tr key={s.slot_time}><td>{s.slot_time?.slice(0,5)}</td><td>{s.reserved}/{s.capacity}</td><td>{s.checked_in}</td><td>{s.completed}</td><td>{s.ineligible}</td><td>{s.no_show}</td></tr>)}</tbody></table></section><section className="card" style={{marginTop:18}}><h2>예약자 구분</h2><div className="admin-grid">{[['예약 병원직원',data.participants.reservation_employee],['예약 방문객',data.participants.reservation_visitor],['비예약 병원직원',data.participants.walkin_employee],['비예약 방문객',data.participants.walkin_visitor]].map(([name,value])=><div className="stat" key={String(name)}><span className="hint">{name}</span><b style={{display:'block',fontSize:'1.25rem',marginTop:7}}>{String(value)}명</b></div>)}</div></section><section className="card" style={{marginTop:18}}><h2>병원직원 근무처별 현황</h2>{data.workplaces.length?<table><thead><tr><th>근무처</th><th>인원</th></tr></thead><tbody>{data.workplaces.map((w:any)=><tr key={w.workplace}><td>{w.workplace}</td><td>{w.count}명</td></tr>)}</tbody></table>:<p className="hint">등록된 병원직원 정보가 없습니다.</p>}</section><section className="card" style={{marginTop:18}}><h2>헌혈완료 직원 명단</h2><p className="hint">소식지 게시용 확인 명단입니다. 방문객은 포함하지 않습니다.</p>{data.completedEmployees.length?<table><thead><tr><th>이름</th><th>근무처</th><th>등록 구분</th></tr></thead><tbody>{data.completedEmployees.map((employee:any,index:number)=><tr key={`${employee.name}-${index}`}><td>{employee.name}</td><td>{employee.workplace}</td><td>{employee.registration_type}</td></tr>)}</tbody></table>:<p className="hint">헌혈완료 처리된 직원이 없습니다.</p>}</section></main>;
}
